# Generated by Django 4.2.2 on 2024-01-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_three', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_change', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_three.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_three.author')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
